### ISSUE TITLE
Transitioning from ng1 using angular-avatar, handling ngUpgrade downgradeComponent situation

### ISSUE THREAD

**Issue by jpike88** [HaithemMosbahi/ngx-avatar#62]
It's not immediately clear how to use this with ngUpgrade, as usually 3rd party components provide the component itself, not a module.

That way, I can use that component in entryComponents, and declare this code in my AppModule:

```
	public ngDoBootstrap() {
		angular.module('').directive('fields', downgradeComponent({
			component: FieldsComponent
		}) as angular.IDirectiveFactory);
	}
```

I tried this PR (https://github.com/HaithemMosbahi/ngx-avatar/pull/48) but the problem is that if I export the component separately, it seems to be an issue:

`Component is part of the declaration of 2 modules`

How can I easily solve this?

**Comment by jpike88** [comment]
Relevant PR?
https://github.com/HaithemMosbahi/ngx-avatar/pull/48

**Comment by HaithemMosbahi** [comment]
Hi,
I am not sure I understand the issue here ! This component was not implemented for ng1, it's for Angular 2+.
The pull request that you mentioned is meant for supporting Angular Elements and not NgUpgrade

**Comment by HaithemMosbahi** [comment]
angular-avatar is a completely different library

**Comment by jpike88** [comment]
> angular-avatar is a completely different library

I'm aware of that, just giving you background

> This component was not implemented for ng1, it's for Angular 2+.

ngUpgrade allows a situation where you don't have to implement a component for ng1 at all, it just works.

https://angular.io/api/upgrade/static/downgradeComponent

Because you're hiding everything in a module, it makes it very difficult to get at the component. This is about adhering to angular 2 design principles, it shouldn't require any knowledge of ng1.

Look, I forked your demo, to show you:

https://stackblitz.com/edit/ngx-avatar-demo-obfbwn

**Comment by HaithemMosbahi** [comment]
Now I understand the problem, the AngularComponent class is needed in order to be able to downgrade it and use it ing ng1.
I will export AvatarComponent class in the next version

**Comment by HaithemMosbahi** [comment]
fixed in version 3.5.0

**Comment by jpike88** [comment]
Not fixed, I get this error now:

> Type AvatarComponent is part of the declarations of 2 modules: AvatarModule and AppModule! Please consider moving AvatarComponent to a higher module that imports AvatarModule and AppModule. You can also create a new NgModule that exports and includes AvatarComponent then import that NgModule in AvatarModule and AppModule

Unless you expect that I do what that error suggests... seems like major overkill for such a minor library though. I don't think requiring developers to do that is a good move, just adds unnecessary complexity to codebases
